Adds searching trace when enter key os pressed
openzipkin/zipkin pull request #2363
Opened 2019-01-24 10:10 UTC by zeagord

2019-01-24 10:20 UTC, codefromthecrypt approved these changes

2019-01-24 10:21 UTC, adriancole commented
cc @making who asked for this in the twitter issues list :D

2019-01-24 13:32 UTC, shakuzen submitted a review, later dismissed

2019-01-24 23:33 UTC, tacigar commented
Thank you!!

2019-01-24 23:40 UTC, tacigar requested changes
I think that it is necessary to handle focus well.

Currently, we can also select dropdown menu by pressing Enter key.
So, If we press Enter key when dropdown menu is opened, both menu-selecting process and fetching process run.
It is not very good for UX...

2019-01-25 00:10 UTC, tacigar commented
For example.

```
class GlobalSearch extends React.Component {
  constructor(props) {
    ...
    this.state = {
      isConditionFocused: false, // <- Add state.
    };
    ...
  }
  ...
  handleKeyPress(event) {
    const { isConditionFocused } = this.state;
    if (event.key === 'Enter' && !isConditionFocused) {
      this.handleSearchButtonClick();
    }
  }
  ...
  handleConditionFocus() {
    this.setState({ isConditionFocused: true });
  }
  handleConditionKeyBlur() {
    this.setState({ isConditionFocused: false });
  }
  handleConditionValueBlur() {
    // Avoid fetching
    setTimeout(() => { this.setState({ isConditionFocused: false }); }, 10);
  }
  ...
  renderSearchCondition(condition, index) {
    ...
    return (
      <SearchCondition
        {...commonProps}
        onKeyFocus={this.handleConditionFocus}
        onValueFocus={this.handleConditionFocus}
        onKeyBlur={this.handleConditionKeyBlur}
        onValueBlur={this.handleConditionValueBlur}
      >
        ...
      </SearchCondition>
    )
    ...
  }
}
```

2019-01-25 05:05 UTC, zeagord commented
> handleConditionValueBlur

Thanks @tacigar

2019-01-25 06:26 UTC, tacigar commented on zipkin-lens/src/components/GlobalSearch/index.js
> +      <SearchCondition
Ah, sorry for omitting code in example.
Please set callback props for `336`-`342` like the following.

```
<SearchCondition
  {...commonProps}
  onKeyFocus={() => {
    fetchAutocompleteValues(condition.key);
    this.handleConditionFocus();
  }
  onValueFocus{() => {
    fetchAutocompleteValues(condition.key);
    this.handleConditionFocus();
  }
  onKeyBlur={this.handleConditionKeyBlur}
  onValueBlur={this.handleConditionValueBlur}
>
  ...
</SearchCondition>
```

2019-01-25 06:29 UTC, tacigar commented on zipkin-lens/src/components/GlobalSearch/index.js
> +  handleKeyPress(event) {
Nit: How about to rename `handleKeyDown` ?

2019-01-25 08:02 UTC, zeagord commented
Makes sense. slSince the keypress event it deprecated. Renaming it to
KeyDown will be a better choice.

On Fri, 25 Jan, 2019, 13:29 tacigar <notifications@github.com wrote:

> *@tacigar* commented on this pull request.
> ------------------------------
>
> In zipkin-lens/src/components/GlobalSearch/index.js
> <https://github.com/openzipkin/zipkin/pull/2363#discussion_r250878582>:
>
> > @@ -145,11 +156,17 @@ class GlobalSearch extends React.Component {
>      });
>    }
>
> +  handleKeyPress(event) {
>
> Nit: How about to rename handleKeyDown ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openzipkin/zipkin/pull/2363#pullrequestreview-196373442>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEgSsCnvTv-6Fzx1GbxWStWIGNxYrEIAks5vGqRagaJpZM4aQiRl>
> .
>

2019-01-26 21:54 UTC, tacigar commented
Thank you!!!
LGTM!!

2019-01-26 21:54 UTC, tacigar approved these changes

2019-01-27 03:56 UTC, merged

2019-01-27 03:57 UTC, adriancole commented
good work compadres

2019-01-27 06:11 UTC, making commented
awesome!

2019-02-01 02:10 UTC, tacigar commented
This PR solves one of #2351 

>  it'd be nice if pressing enter executed the search