fix: STORAGE_METHOD -> STORAGE_TYPE
openzipkin/zipkin pull request #3417
Opened 2022-01-25 09:39 UTC by jcchavezs

2022-01-25 09:41 UTC, jonkerj requested changes
You need to bump the version (just increase the patch level) in `Chart.yaml` as well

2022-01-26 11:40 UTC, jonkerj commented
I really like the way this is going. Don't forget to also update the chart version (`.version`).

2022-01-26 23:32 UTC, jcchavezs commented on charts/zipkin/README.md
> +You can then run `helm search repo zipkin` to see the charts.
```suggestion
You can then run `helm search repo openzipkin` to see the charts.
```

2022-01-26 23:51 UTC, jcchavezs commented
> You need to bump the version (just increase the patch level) in Chart.yaml as well

I will do a chart release after merge.

2022-01-27 13:12 UTC, jcchavezs commented on .github/workflows/helm_release.yml
> +# We release helm_charts into https://openzipkin.github.com/index.yaml
```suggestion
# We release helm_charts into https://github.com/openzipkin/zipkin/blob/gh-pages/index.yaml
```

2022-01-27 14:35 UTC, merged